version: '3'

services:
  app:
    image: dh1011/start-ichi:latest
    ports:
      - "5000:5000"
    volumes:
      - ./app/server/data:/app/data:rw
    environment:
      - FLASK_ENV=production
    user: "1000:1000"
    restart: unless-stopped

volumes:
  data: