version: '3'

services:
  start-ichi:
    # image: dh1011/start-ichi:latest
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - data:/app/server/data
    environment:
      - START_ICHI_PASSWORD=admin
      - FLASK_SECRET_KEY=dev
    restart: unless-stopped

volumes:
  data: